# docker-compose.yml
version: '3.8'

services:
  api:
    build: .
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  dashboard:
    build: .
    command: python backend/dashboard.py
    ports:
      - "8050:8050"
    volumes:
      - .:/app
